AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This repos deployed resource

Parameters:
  CodeBuildComputeType:
    Type: String
    Description: "The compute engine to run the build. Default is 'BUILD_GENERAL1_SMALL'"
    Default: BUILD_GENERAL1_SMALL
    AllowedValues: [ BUILD_GENERAL1_SMALL, BUILD_GENERAL1_MEDIUM, BUILD_GENERAL1_LARGE, BUILD_GENERAL1_2XLARGE ]

Resources:

  # Pipeline Role
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /service-role/
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonSSMReadOnlyAccess"
        - !Sub "arn:${AWS::Partition}:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
      Policies:
        - PolicyName: "MyMoneyCloudWatchMetrics"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "cloudwatch:PutMetricData"
                Resource: "*"
        - PolicyName: "CodeBuildBasePolicy"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource:
                  - !Sub "arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*"
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
        - PolicyName: CodeBuildArtifactsBucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:PutObject"
                Resource:
                  - "*"
        - PolicyName: CodeBuildManagedSecretPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: !Sub "arn:${AWS::Partition}:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CodeBuild/*"
                Action: ssm:GetParameters
        - PolicyName: AssumeExecutionRoles
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - sts:AssumeRole
                Effect: Allow
                Resource: "*"

  # CODEBUILD PROJECTS
  BuildAndPackageForJava17:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: aws/codebuild/standard:6.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: arn:aws:s3:::danieljigin-service-templates/buildspec_java17_build_package.yml

  # CODEBUILD PROJECTS
  BuildAndPackageForJava11:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: !Ref CodeBuildComputeType
        Image: aws/codebuild/standard:6.0
        PrivilegedMode: true
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: arn:aws:s3:::danieljigin-service-templates/buildspec_java11_build_package.yml

Outputs:
  Java17Builder:
    Value: !Ref BuildAndPackageForJava17
    Export:
      Name: BuildAndPackageForJava17
  Java11Builder:
    Value: !Ref BuildAndPackageForJava11
    Export:
      Name: BuildAndPackageForJava11

